# Generated by Django 5.0.1 on 2024-01-15 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='data',
        ),
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 6, 59, 34, 510112, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
